from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Protocol
from uuid import UUID

from app.domain.dtos import InvoiceDTO, PaymentDTO, SchoolDTO, StudentDTO


class SchoolRepo(Protocol):
    def create(self, data: Mapping[str, object]) -> SchoolDTO: ...

    def list_all(self, *, offset: int, limit: int) -> list[SchoolDTO]: ...

    def get_by_id(self, school_id: UUID) -> SchoolDTO | None: ...

    def update(self, school_id: UUID, data: Mapping[str, object]) -> SchoolDTO | None: ...

    def delete(self, school_id: UUID) -> bool: ...


class StudentRepo(Protocol):
    def create(self, data: Mapping[str, object]) -> StudentDTO: ...

    def list_all(self, *, offset: int, limit: int) -> list[StudentDTO]: ...

    def list_by_school_id(self, school_id: UUID, *, offset: int = 0, limit: int = 100) -> list[StudentDTO]: ...

    def get_by_id(self, student_id: UUID) -> StudentDTO | None: ...

    def update(self, student_id: UUID, data: Mapping[str, object]) -> StudentDTO | None: ...

    def delete(self, student_id: UUID) -> bool: ...


class InvoiceRepo(Protocol):
    def create(self, data: Mapping[str, object]) -> InvoiceDTO: ...

    def list_all(self, *, offset: int, limit: int) -> list[InvoiceDTO]: ...

    def list_by_student_id(self, student_id: UUID) -> list[InvoiceDTO]: ...

    def list_by_student_ids(self, student_ids: Sequence[UUID]) -> list[InvoiceDTO]: ...

    def get_by_id(self, invoice_id: UUID) -> InvoiceDTO | None: ...

    def update(self, invoice_id: UUID, data: Mapping[str, object]) -> InvoiceDTO | None: ...

    def delete(self, invoice_id: UUID) -> bool: ...


class PaymentRepo(Protocol):
    def create(self, data: Mapping[str, object]) -> PaymentDTO: ...

    def list_all(self, *, offset: int, limit: int) -> list[PaymentDTO]: ...

    def list_by_invoice_id(self, invoice_id: UUID) -> list[PaymentDTO]: ...

    def list_by_invoice_ids(self, invoice_ids: Sequence[UUID]) -> list[PaymentDTO]: ...

    def get_by_id(self, payment_id: UUID) -> PaymentDTO | None: ...

    def update(self, payment_id: UUID, data: Mapping[str, object]) -> PaymentDTO | None: ...

    def delete(self, payment_id: UUID) -> bool: ...
